"""add weeks

Revision ID: 086223921e84
Revises: 74e10d47e719
Create Date: 2026-06-24 17:21:38.255220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '086223921e84'
down_revision: Union[str, Sequence[str], None] = '74e10d47e719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recommended_date', sa.String(), nullable=True),
    sa.Column('phase', sa.Enum('adaptation', 'accumulation', 'transmutation', 'realization', name='mesocyclephase'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position', deferrable=True, initially='DEFERRED', name='uq_week_position')
    )
    op.create_table('week_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    # trainingcategory/trainingsubtype already exist (created with training_sessions),
    # so reference them without re-creating the types.
    sa.Column('category', postgresql.ENUM('gym', 'pool', 'cardio', name='trainingcategory', create_type=False), nullable=False),
    sa.Column('subtype', postgresql.ENUM('adaptation', 'accumulation', 'transmutation', 'realization', 'endurance', 'alactic', 'aerobic', 'anaerobic', name='trainingsubtype', create_type=False), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_week_requirements_week_id'), 'week_requirements', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_week_requirements_week_id'), table_name='week_requirements')
    op.drop_table('week_requirements')
    op.drop_table('weeks')
    # Drop the new enum type (trainingcategory/trainingsubtype are shared, leave them).
    sa.Enum(name='mesocyclephase').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
