"""add session logs

Revision ID: 0c88aae1b52d
Revises: 086223921e84
Create Date: 2026-06-24 18:51:44.536370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c88aae1b52d'
down_revision: Union[str, Sequence[str], None] = '086223921e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('training_session_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_logs_athlete_id'), 'session_logs', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_session_logs_training_session_id'), 'session_logs', ['training_session_id'], unique=False)
    op.create_table('session_log_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('planned_exercise_name', sa.String(), nullable=False),
    sa.Column('performed_exercise_id', sa.Uuid(), nullable=True),
    sa.Column('performed_exercise_name', sa.String(), nullable=False),
    sa.Column('is_alternative', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['session_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_exercise_id'], ['exercises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_log_entries_log_id'), 'session_log_entries', ['log_id'], unique=False)
    op.create_table('session_log_parameter_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Uuid(), nullable=True),
    sa.Column('parameter_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['session_log_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parameter_id'], ['exercise_parameters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_log_parameter_values_entry_id'), 'session_log_parameter_values', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_log_parameter_values_entry_id'), table_name='session_log_parameter_values')
    op.drop_table('session_log_parameter_values')
    op.drop_index(op.f('ix_session_log_entries_log_id'), table_name='session_log_entries')
    op.drop_table('session_log_entries')
    op.drop_index(op.f('ix_session_logs_training_session_id'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_athlete_id'), table_name='session_logs')
    op.drop_table('session_logs')
    # ### end Alembic commands ###
