"""add speed test logs

Revision ID: 213ea6992add
Revises: 531ec2add4be
Create Date: 2026-06-26 16:28:38.756335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213ea6992add'
down_revision: Union[str, Sequence[str], None] = '531ec2add4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_test_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=True),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speed_test_logs_athlete_id'), 'speed_test_logs', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_speed_test_logs_week_id'), 'speed_test_logs', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speed_test_logs_week_id'), table_name='speed_test_logs')
    op.drop_index(op.f('ix_speed_test_logs_athlete_id'), table_name='speed_test_logs')
    op.drop_table('speed_test_logs')
    # ### end Alembic commands ###
