"""add gym facilities

Revision ID: 25c5a575dc7e
Revises: ed90b6755c0b
Create Date: 2026-06-30 18:27:57.494327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c5a575dc7e'
down_revision: Union[str, Sequence[str], None] = 'ed90b6755c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_facilities_name'), 'gym_facilities', ['name'], unique=True)
    op.create_table('exercise_gym_facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('gym_facility_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_facility_id'], ['gym_facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'gym_facility_id', name='uq_exercise_gym_facility')
    )
    op.create_index(op.f('ix_exercise_gym_facilities_exercise_id'), 'exercise_gym_facilities', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_gym_facilities_gym_facility_id'), 'exercise_gym_facilities', ['gym_facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_gym_facilities_gym_facility_id'), table_name='exercise_gym_facilities')
    op.drop_index(op.f('ix_exercise_gym_facilities_exercise_id'), table_name='exercise_gym_facilities')
    op.drop_table('exercise_gym_facilities')
    op.drop_index(op.f('ix_gym_facilities_name'), table_name='gym_facilities')
    op.drop_table('gym_facilities')
    # ### end Alembic commands ###
