"""rework session log entries

Revision ID: 3e84861a01a8
Revises: 0c88aae1b52d
Create Date: 2026-06-25 08:56:45.019388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e84861a01a8'
down_revision: Union[str, Sequence[str], None] = '0c88aae1b52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column doesn't auto-create the enum type (unlike create_table), so do it
    # explicitly. The log tables are empty, so NOT NULL adds are safe.
    sa.Enum('done', 'skipped', name='sessionlogaction').create(op.get_bind(), checkfirst=True)
    op.add_column('session_log_entries', sa.Column('action', sa.Enum('done', 'skipped', name='sessionlogaction', create_type=False), nullable=False))
    op.add_column('session_log_entries', sa.Column('planned_exercise_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_session_log_entries_planned_exercise_id'), 'session_log_entries', ['planned_exercise_id'], unique=False)
    op.drop_constraint(op.f('session_log_entries_performed_exercise_id_fkey'), 'session_log_entries', type_='foreignkey')
    op.create_foreign_key(None, 'session_log_entries', 'exercises', ['performed_exercise_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'session_log_entries', 'exercises', ['planned_exercise_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_log_entries', 'planned_exercise_name')
    op.drop_column('session_log_entries', 'is_alternative')
    op.drop_column('session_log_entries', 'performed_exercise_name')
    op.alter_column('session_log_parameter_values', 'parameter_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_session_log_parameter_values_parameter_id'), 'session_log_parameter_values', ['parameter_id'], unique=False)
    op.drop_constraint(op.f('session_log_parameter_values_parameter_id_fkey'), 'session_log_parameter_values', type_='foreignkey')
    op.create_foreign_key(None, 'session_log_parameter_values', 'exercise_parameters', ['parameter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_log_parameter_values', 'parameter_name')
    op.add_column('session_logs', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_logs', 'note')
    op.add_column('session_log_parameter_values', sa.Column('parameter_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session_log_parameter_values', type_='foreignkey')
    op.create_foreign_key(op.f('session_log_parameter_values_parameter_id_fkey'), 'session_log_parameter_values', 'exercise_parameters', ['parameter_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_session_log_parameter_values_parameter_id'), table_name='session_log_parameter_values')
    op.alter_column('session_log_parameter_values', 'parameter_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('session_log_entries', sa.Column('performed_exercise_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('session_log_entries', sa.Column('is_alternative', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('session_log_entries', sa.Column('planned_exercise_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session_log_entries', type_='foreignkey')
    op.drop_constraint(None, 'session_log_entries', type_='foreignkey')
    op.create_foreign_key(op.f('session_log_entries_performed_exercise_id_fkey'), 'session_log_entries', 'exercises', ['performed_exercise_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_session_log_entries_planned_exercise_id'), table_name='session_log_entries')
    op.drop_column('session_log_entries', 'planned_exercise_id')
    op.drop_column('session_log_entries', 'action')
    sa.Enum(name='sessionlogaction').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
