"""add speed test warmup pointer

Revision ID: 531ec2add4be
Revises: cfc8151ea9f6
Create Date: 2026-06-26 16:14:40.218063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531ec2add4be'
down_revision: Union[str, Sequence[str], None] = 'cfc8151ea9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_test_warmup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('training_session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speed_test_warmup')
    # ### end Alembic commands ###
