"""add strength test items

Revision ID: 55ee7dd6f179
Revises: 55cb007988b9
Create Date: 2026-06-26 14:13:36.030112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ee7dd6f179'
down_revision: Union[str, Sequence[str], None] = '55cb007988b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strength_test_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('weight_multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strength_test_items_exercise_id'), 'strength_test_items', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strength_test_items_exercise_id'), table_name='strength_test_items')
    op.drop_table('strength_test_items')
    # ### end Alembic commands ###
