"""add training_item target_time_formula

Revision ID: 596c6a74c0c3
Revises: 7cbb521d007a
Create Date: 2026-08-17 19:52:09.015379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596c6a74c0c3'
down_revision: Union[str, Sequence[str], None] = '7cbb521d007a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_items', sa.Column('target_time_formula', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_items', 'target_time_formula')
    # ### end Alembic commands ###
