"""add complete flag to session logs

Revision ID: 633cfe578802
Revises: f5645c531c4d
Create Date: 2026-07-27 08:09:50.696316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633cfe578802'
down_revision: Union[str, Sequence[str], None] = 'f5645c531c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_logs', sa.Column('complete', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_logs', 'complete')
    # ### end Alembic commands ###
