"""add bodyweight logs

Revision ID: 6be286d81b4e
Revises: a113a60b2679
Create Date: 2026-06-26 11:36:06.426765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be286d81b4e'
down_revision: Union[str, Sequence[str], None] = 'a113a60b2679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodyweight_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bodyweight_logs_athlete_id'), 'bodyweight_logs', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bodyweight_logs_athlete_id'), table_name='bodyweight_logs')
    op.drop_table('bodyweight_logs')
    # ### end Alembic commands ###
