"""add exercise relations

Revision ID: 748d975ae567
Revises: f76c6502c994
Create Date: 2026-06-24 07:30:39.788686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748d975ae567'
down_revision: Union[str, Sequence[str], None] = 'f76c6502c994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('related_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'related_exercise_id', name='uq_exercise_relation')
    )
    op.create_index(op.f('ix_exercise_relations_exercise_id'), 'exercise_relations', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_relations_related_exercise_id'), 'exercise_relations', ['related_exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_relations_related_exercise_id'), table_name='exercise_relations')
    op.drop_index(op.f('ix_exercise_relations_exercise_id'), table_name='exercise_relations')
    op.drop_table('exercise_relations')
    # ### end Alembic commands ###
