"""add training item load percentage

Revision ID: 76f55fc4d72b
Revises: 8a98b589b6b4
Create Date: 2026-06-26 14:53:21.401199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f55fc4d72b'
down_revision: Union[str, Sequence[str], None] = '8a98b589b6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_items', sa.Column('load_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_items', 'load_percentage')
    # ### end Alembic commands ###
