"""add training_item_id to session log entries

Revision ID: 7cbb521d007a
Revises: eaa5ddd0d313
Create Date: 2026-07-27 11:42:22.287965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbb521d007a'
down_revision: Union[str, Sequence[str], None] = 'eaa5ddd0d313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_log_entries', sa.Column('training_item_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_log_entries', 'training_item_id')
    # ### end Alembic commands ###
