"""add exercise parameters

Revision ID: 7e57f0cc2a7e
Revises: 748d975ae567
Create Date: 2026-06-24 09:16:44.055356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e57f0cc2a7e'
down_revision: Union[str, Sequence[str], None] = '748d975ae567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_parameters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'name', name='uq_exercise_parameter_name')
    )
    op.create_index(op.f('ix_exercise_parameters_exercise_id'), 'exercise_parameters', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_parameters_exercise_id'), table_name='exercise_parameters')
    op.drop_table('exercise_parameters')
    # ### end Alembic commands ###
