"""add exercise media keys

Revision ID: 8a4b001d80d4
Revises: 427c6d28a381
Create Date: 2026-06-23 11:06:01.358674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4b001d80d4'
down_revision: Union[str, Sequence[str], None] = '427c6d28a381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('thumbnail_key', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('video_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'video_key')
    op.drop_column('exercises', 'thumbnail_key')
    # ### end Alembic commands ###
