"""add strength test logs

Revision ID: 8a98b589b6b4
Revises: 55ee7dd6f179
Create Date: 2026-06-26 14:27:04.327312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a98b589b6b4'
down_revision: Union[str, Sequence[str], None] = '55ee7dd6f179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strength_test_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=True),
    sa.Column('bodyweight_kg', sa.Float(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strength_test_logs_athlete_id'), 'strength_test_logs', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_strength_test_logs_week_id'), 'strength_test_logs', ['week_id'], unique=False)
    op.create_table('strength_test_log_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=False),
    sa.Column('actual_weight_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_id'], ['strength_test_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strength_test_log_entries_exercise_id'), 'strength_test_log_entries', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_strength_test_log_entries_log_id'), 'strength_test_log_entries', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strength_test_log_entries_log_id'), table_name='strength_test_log_entries')
    op.drop_index(op.f('ix_strength_test_log_entries_exercise_id'), table_name='strength_test_log_entries')
    op.drop_table('strength_test_log_entries')
    op.drop_index(op.f('ix_strength_test_logs_week_id'), table_name='strength_test_logs')
    op.drop_index(op.f('ix_strength_test_logs_athlete_id'), table_name='strength_test_logs')
    op.drop_table('strength_test_logs')
    # ### end Alembic commands ###
