"""add cardio trainings

Revision ID: 9749d67e4f42
Revises: cfd6d4298c46
Create Date: 2026-06-24 16:23:19.306362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9749d67e4f42'
down_revision: Union[str, Sequence[str], None] = 'cfd6d4298c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardio_trainings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subtype', sa.Enum('aerobic', 'anaerobic', name='cardiosubtype'), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtype', 'position', deferrable=True, initially='DEFERRED', name='uq_cardio_training_position')
    )
    op.create_table('cardio_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('training_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('block', 'note', name='cardioitemkind'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('repeats', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['cardio_trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardio_items_training_id'), 'cardio_items', ['training_id'], unique=False)
    op.create_table('cardio_intervals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('effort', 'rest', name='cardiointervalkind'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('intensity_pct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['cardio_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardio_intervals_item_id'), 'cardio_intervals', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cardio_intervals_item_id'), table_name='cardio_intervals')
    op.drop_table('cardio_intervals')
    op.drop_index(op.f('ix_cardio_items_training_id'), table_name='cardio_items')
    op.drop_table('cardio_items')
    op.drop_table('cardio_trainings')
    # Drop the enum types too — create_table only auto-creates them on upgrade, so
    # downgrade must drop them explicitly or a re-upgrade fails on "already exists".
    sa.Enum(name='cardiointervalkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cardioitemkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cardiosubtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
