"""add cardio session logs

Revision ID: a113a60b2679
Revises: f27c6170fb63
Create Date: 2026-06-26 09:50:57.329165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a113a60b2679'
down_revision: Union[str, Sequence[str], None] = 'f27c6170fb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardio_session_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cardio_training_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=True),
    sa.Column('exercise', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cardio_training_id'], ['cardio_trainings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardio_session_logs_athlete_id'), 'cardio_session_logs', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_cardio_session_logs_cardio_training_id'), 'cardio_session_logs', ['cardio_training_id'], unique=False)
    op.create_index(op.f('ix_cardio_session_logs_week_id'), 'cardio_session_logs', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cardio_session_logs_week_id'), table_name='cardio_session_logs')
    op.drop_index(op.f('ix_cardio_session_logs_cardio_training_id'), table_name='cardio_session_logs')
    op.drop_index(op.f('ix_cardio_session_logs_athlete_id'), table_name='cardio_session_logs')
    op.drop_table('cardio_session_logs')
    # ### end Alembic commands ###
