"""add training session position

Revision ID: cfd6d4298c46
Revises: 7e57f0cc2a7e
Create Date: 2026-06-24 14:44:57.310098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd6d4298c46'
down_revision: Union[str, Sequence[str], None] = '7e57f0cc2a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.create_unique_constraint('uq_training_session_position', 'training_sessions', ['category', 'subtype', 'position'], deferrable=True, initially='DEFERRED')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_training_session_position', 'training_sessions', type_='unique')
    op.drop_column('training_sessions', 'position')
    # ### end Alembic commands ###
