"""one partial session log per session

Revision ID: eaa5ddd0d313
Revises: 633cfe578802
Create Date: 2026-07-27 11:30:24.633164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa5ddd0d313'
down_revision: Union[str, Sequence[str], None] = '633cfe578802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_session_log_one_partial_per_session', 'session_logs', ['athlete_id', 'training_session_id'], unique=True, postgresql_where=sa.text('complete = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_session_log_one_partial_per_session', table_name='session_logs', postgresql_where=sa.text('complete = false'))
    # ### end Alembic commands ###
