"""add gym materials

Revision ID: ed90b6755c0b
Revises: e2528b372dc4
Create Date: 2026-06-30 14:34:04.535229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed90b6755c0b'
down_revision: Union[str, Sequence[str], None] = 'e2528b372dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_materials_name'), 'gym_materials', ['name'], unique=True)
    op.create_table('exercise_gym_materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('gym_material_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_material_id'], ['gym_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'gym_material_id', name='uq_exercise_gym_material')
    )
    op.create_index(op.f('ix_exercise_gym_materials_exercise_id'), 'exercise_gym_materials', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_gym_materials_gym_material_id'), 'exercise_gym_materials', ['gym_material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_gym_materials_gym_material_id'), table_name='exercise_gym_materials')
    op.drop_index(op.f('ix_exercise_gym_materials_exercise_id'), table_name='exercise_gym_materials')
    op.drop_table('exercise_gym_materials')
    op.drop_index(op.f('ix_gym_materials_name'), table_name='gym_materials')
    op.drop_table('gym_materials')
    # ### end Alembic commands ###
