"""add session log week link

Revision ID: f27c6170fb63
Revises: 3e84861a01a8
Create Date: 2026-06-25 11:57:41.747571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27c6170fb63'
down_revision: Union[str, Sequence[str], None] = '3e84861a01a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_logs', sa.Column('week_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_session_logs_week_id'), 'session_logs', ['week_id'], unique=False)
    op.create_foreign_key(None, 'session_logs', 'weeks', ['week_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_logs', type_='foreignkey')
    op.drop_index(op.f('ix_session_logs_week_id'), table_name='session_logs')
    op.drop_column('session_logs', 'week_id')
    # ### end Alembic commands ###
