"""add lactic acid test logs

Revision ID: f5645c531c4d
Revises: b3f9c2e1a7d4
Create Date: 2026-07-08 09:38:43.227041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5645c531c4d'
down_revision: Union[str, Sequence[str], None] = 'b3f9c2e1a7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the 'lactic' value to trainingsubtype, for the per-week lactic-acid test
    # (category Prueba / subtype Ácido láctico). Mirrors how 'speed' was added.
    op.execute("ALTER TYPE trainingsubtype ADD VALUE IF NOT EXISTS 'lactic'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lactic_acid_personal_best_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=True),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lactic_acid_personal_best_logs_athlete_id'), 'lactic_acid_personal_best_logs', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_lactic_acid_personal_best_logs_week_id'), 'lactic_acid_personal_best_logs', ['week_id'], unique=False)
    op.create_table('lactic_acid_test_result_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=True),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lactic_acid_test_result_logs_athlete_id'), 'lactic_acid_test_result_logs', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_lactic_acid_test_result_logs_week_id'), 'lactic_acid_test_result_logs', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lactic_acid_test_result_logs_week_id'), table_name='lactic_acid_test_result_logs')
    op.drop_index(op.f('ix_lactic_acid_test_result_logs_athlete_id'), table_name='lactic_acid_test_result_logs')
    op.drop_table('lactic_acid_test_result_logs')
    op.drop_index(op.f('ix_lactic_acid_personal_best_logs_week_id'), table_name='lactic_acid_personal_best_logs')
    op.drop_index(op.f('ix_lactic_acid_personal_best_logs_athlete_id'), table_name='lactic_acid_personal_best_logs')
    op.drop_table('lactic_acid_personal_best_logs')
    # ### end Alembic commands ###
