"""add training sessions

Revision ID: f76c6502c994
Revises: 8a4b001d80d4
Create Date: 2026-06-23 13:55:36.163995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76c6502c994'
down_revision: Union[str, Sequence[str], None] = '8a4b001d80d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('gym', 'pool', 'cardio', name='trainingcategory'), nullable=False),
    sa.Column('subtype', sa.Enum('adaptation', 'accumulation', 'transmutation', 'realization', 'endurance', 'alactic', 'aerobic', 'anaerobic', name='trainingsubtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_blocks_session_id'), 'training_blocks', ['session_id'], unique=False)
    op.create_table('training_sub_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['training_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sub_blocks_block_id'), 'training_sub_blocks', ['block_id'], unique=False)
    op.create_table('training_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub_block_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('series', 'note', name='trainingitemkind'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('effort', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_block_id'], ['training_sub_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_items_sub_block_id'), 'training_items', ['sub_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_items_sub_block_id'), table_name='training_items')
    op.drop_table('training_items')
    op.drop_index(op.f('ix_training_sub_blocks_block_id'), table_name='training_sub_blocks')
    op.drop_table('training_sub_blocks')
    op.drop_index(op.f('ix_training_blocks_session_id'), table_name='training_blocks')
    op.drop_table('training_blocks')
    op.drop_table('training_sessions')
    # Drop the enum types too — create_table only auto-creates them on upgrade, so
    # without this a re-upgrade fails with "type already exists".
    sa.Enum(name='trainingitemkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='trainingsubtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='trainingcategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
