/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/db-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Db Health */
        get: operations["db_health_db_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Existing users plus invitations that haven't been accepted yet, optionally
         *     filtered. `status` scopes the result: active/inactive look at users only,
         *     invitation_pending/expired look at invitations only.
         */
        get: operations["list_users_auth_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Detail
         * @description Detail for a directory entry — the id may be a user or an invitation.
         */
        get: operations["get_user_detail_auth_users__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Partially update a user. Only real users are updatable (not invitations).
         */
        patch: operations["update_user_auth_users__user_id__patch"];
        trace?: never;
    };
    "/auth/users/{user_id}/reset-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate User Reset Code
         * @description Issue a single-use password-reset code for a user. The admin shares the
         *     returned code with them out-of-band; only its hash is stored.
         */
        post: operations["generate_user_reset_code_auth_users__user_id__reset_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Public: reset a password using the admin-issued code. The same generic
         *     error is returned for any failure so we don't reveal which part was wrong.
         */
        post: operations["reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Invitation */
        post: operations["create_invitation_auth_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations/{invitation_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Invitation
         * @description Issue a fresh token and reset the expiry for an existing invitation
         *     (e.g. when the previous link expired). Returns the new link once.
         */
        post: operations["regenerate_invitation_auth_invitations__invitation_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Invitation */
        get: operations["get_invitation_auth_invitations__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invitation */
        post: operations["accept_invitation_auth_invitations__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/media-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Media Upload
         * @description Mint a presigned POST so the admin's browser can upload a thumbnail or
         *     video straight to S3. Returns the object key to store on save.
         */
        post: operations["create_media_upload_exercises_media_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exercises
         * @description All exercises, filterable by name search and type. Visible to any user.
         */
        get: operations["list_exercises_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exercise
         * @description A single exercise by id. Visible to any authenticated user.
         */
        get: operations["get_exercise_exercises__exercise_id__get"];
        /** Update Exercise */
        put: operations["update_exercise_exercises__exercise_id__put"];
        post?: never;
        /** Delete Exercise */
        delete: operations["delete_exercise_exercises__exercise_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trainings
         * @description All training sessions, filterable by title search, category and subtype.
         *     Visible to any authenticated user.
         */
        get: operations["list_trainings_trainings_get"];
        put?: never;
        /** Create Training */
        post: operations["create_training_trainings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainings/{training_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Training
         * @description A single training session (with its blocks) by id. Visible to any user.
         */
        get: operations["get_training_trainings__training_id__get"];
        /** Update Training */
        put: operations["update_training_trainings__training_id__put"];
        post?: never;
        /** Delete Training */
        delete: operations["delete_training_trainings__training_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvitationRequest */
        AcceptInvitationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** BlockInput */
        BlockInput: {
            /** Name */
            name: string;
            /**
             * Sub Blocks
             * @default []
             */
            sub_blocks: components["schemas"]["SubBlockInput"][];
        };
        /** BlockResponse */
        BlockResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Sub Blocks
             * @default []
             */
            sub_blocks: components["schemas"]["SubBlockResponse"][];
        };
        /** CreateExerciseRequest */
        CreateExerciseRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            type: components["schemas"]["ExerciseType"];
            /** Thumbnail Key */
            thumbnail_key?: string | null;
            /** Video Key */
            video_key?: string | null;
            /**
             * Related Exercises
             * @default []
             */
            related_exercises: components["schemas"]["RelatedExerciseInput"][];
            /**
             * Parameters
             * @default []
             */
            parameters: components["schemas"]["ParameterInput"][];
        };
        /** CreateInvitationRequest */
        CreateInvitationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** CreateTrainingRequest */
        CreateTrainingRequest: {
            category: components["schemas"]["TrainingCategory"];
            subtype: components["schemas"]["TrainingSubtype"];
            /** Title */
            title?: string | null;
            /**
             * Blocks
             * @default []
             */
            blocks: components["schemas"]["BlockInput"][];
        };
        /**
         * DirectoryEntryResponse
         * @description A row in the admin users table: an existing user or a pending invitation.
         */
        DirectoryEntryResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["DirectoryStatus"];
        };
        /**
         * DirectoryStatus
         * @description Status shown in the admin users table — covers both real users and the
         *     pending/expired invitations that haven't become users yet.
         * @enum {string}
         */
        DirectoryStatus: "active" | "inactive" | "invitation_pending" | "invitation_expired";
        /** ExerciseResponse */
        ExerciseResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            type: components["schemas"]["ExerciseType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Thumbnail Key */
            thumbnail_key?: string | null;
            /** Video Key */
            video_key?: string | null;
            /**
             * Related Exercises
             * @default []
             */
            related_exercises: components["schemas"]["RelatedExerciseResponse"][];
            /**
             * Parameters
             * @default []
             */
            parameters: components["schemas"]["ParameterResponse"][];
            /** Thumbnail Url */
            readonly thumbnail_url: string | null;
            /** Video Url */
            readonly video_url: string | null;
        };
        /**
         * ExerciseType
         * @enum {string}
         */
        ExerciseType: "gym" | "pool";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * InvitationInfo
         * @description Public details of a pending invitation, for the accept screen.
         */
        InvitationInfo: {
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * InvitationResponse
         * @description Returned once on creation. `token` is the raw value to share; it is never
         *     stored (only its hash) and cannot be retrieved again.
         */
        InvitationResponse: {
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Token */
            token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MediaKind
         * @enum {string}
         */
        MediaKind: "thumbnail" | "video";
        /** MediaUploadRequest */
        MediaUploadRequest: {
            kind: components["schemas"]["MediaKind"];
            /** Content Type */
            content_type: string;
        };
        /**
         * MediaUploadResponse
         * @description A presigned POST the client uses to upload one file directly to S3, plus
         *     the object key to store on the exercise once the upload succeeds.
         */
        MediaUploadResponse: {
            /** Key */
            key: string;
            /** Url */
            url: string;
            /** Fields */
            fields: {
                [key: string]: string;
            };
        };
        /** Page[DirectoryEntryResponse] */
        Page_DirectoryEntryResponse_: {
            /** Items */
            items: components["schemas"]["DirectoryEntryResponse"][];
            /** Total Count */
            total_count: number;
        };
        /** Page[ExerciseResponse] */
        Page_ExerciseResponse_: {
            /** Items */
            items: components["schemas"]["ExerciseResponse"][];
            /** Total Count */
            total_count: number;
        };
        /** Page[TrainingSessionResponse] */
        Page_TrainingSessionResponse_: {
            /** Items */
            items: components["schemas"]["TrainingSessionResponse"][];
            /** Total Count */
            total_count: number;
        };
        /** ParameterInput */
        ParameterInput: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ParameterResponse */
        ParameterResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** RelatedExerciseInput */
        RelatedExerciseInput: {
            /**
             * Related Exercise Id
             * Format: uuid
             */
            related_exercise_id: string;
            /** Note */
            note?: string | null;
        };
        /**
         * RelatedExerciseResponse
         * @description An alternative/related exercise as shown on the owning exercise: the target's
         *     id + name (to render and round-trip through the form), its thumbnail, plus the note.
         */
        RelatedExerciseResponse: {
            /** Related Exercise Id */
            related_exercise_id: string;
            /** Related Exercise Name */
            related_exercise_name: string;
            /** Related Exercise Thumbnail Url */
            related_exercise_thumbnail_url: string | null;
            /** Note */
            note: string | null;
        };
        /**
         * ResetCodeResponse
         * @description Returned once when an admin generates a reset code; only its hash is stored.
         */
        ResetCodeResponse: {
            /** Code */
            code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Code */
            code: string;
            /** Password */
            password: string;
        };
        /** SubBlockInput */
        SubBlockInput: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** SubBlockResponse */
        SubBlockResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
        };
        /**
         * TrainingCategory
         * @enum {string}
         */
        TrainingCategory: "gym" | "pool" | "cardio";
        /**
         * TrainingSessionDetailResponse
         * @description Detail view: the session plus its ordered blocks.
         */
        TrainingSessionDetailResponse: {
            /** Id */
            id: string;
            category: components["schemas"]["TrainingCategory"];
            subtype: components["schemas"]["TrainingSubtype"];
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Blocks
             * @default []
             */
            blocks: components["schemas"]["BlockResponse"][];
        };
        /**
         * TrainingSessionResponse
         * @description List view: the session itself, without its block tree.
         */
        TrainingSessionResponse: {
            /** Id */
            id: string;
            category: components["schemas"]["TrainingCategory"];
            subtype: components["schemas"]["TrainingSubtype"];
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TrainingSubtype
         * @enum {string}
         */
        TrainingSubtype: "adaptation" | "accumulation" | "transmutation" | "realization" | "endurance" | "alactic" | "aerobic" | "anaerobic";
        /** UpdateExerciseRequest */
        UpdateExerciseRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            type: components["schemas"]["ExerciseType"];
            /** Thumbnail Key */
            thumbnail_key?: string | null;
            /** Video Key */
            video_key?: string | null;
            /**
             * Related Exercises
             * @default []
             */
            related_exercises: components["schemas"]["RelatedExerciseInput"][];
            /**
             * Parameters
             * @default []
             */
            parameters: components["schemas"]["ParameterInput"][];
        };
        /** UpdateTrainingRequest */
        UpdateTrainingRequest: {
            category: components["schemas"]["TrainingCategory"];
            subtype: components["schemas"]["TrainingSubtype"];
            /** Title */
            title?: string | null;
            /**
             * Blocks
             * @default []
             */
            blocks: components["schemas"]["BlockInput"][];
        };
        /**
         * UpdateUserRequest
         * @description Partial update for a user. Only `status` for now; more fields can be added.
         */
        UpdateUserRequest: {
            status?: components["schemas"]["DirectoryStatus"] | null;
        };
        /**
         * UserDetailResponse
         * @description Full detail for a single directory entry (a user or an invitation).
         */
        UserDetailResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["DirectoryStatus"];
            /** Created At */
            created_at?: string | null;
            /** Invited By Email */
            invited_by_email?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "member";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    db_health_db_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_users_auth_users_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                role?: components["schemas"]["UserRole"] | null;
                status?: components["schemas"]["DirectoryStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DirectoryEntryResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_detail_auth_users__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_auth_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_user_reset_code_auth_users__user_id__reset_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_auth_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_invitation_auth_invitations__invitation_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invitation_auth_invitations__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_auth_invitations__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_media_upload_exercises_media_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_exercises_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                type?: components["schemas"]["ExerciseType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExerciseResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExerciseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_exercises__exercise_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExerciseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exercise_exercises__exercise_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trainings_trainings_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                category?: components["schemas"]["TrainingCategory"] | null;
                subtype?: components["schemas"]["TrainingSubtype"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TrainingSessionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_training_trainings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrainingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingSessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_trainings__training_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingSessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_training_trainings__training_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrainingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingSessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_training_trainings__training_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
